-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ameliyat
(
    ameliyat_id serial NOT NULL,
    hasta_id integer,
    doktor_id integer,
    hemsire_id integer,
    ameliyatturu character varying(50) COLLATE pg_catalog."default",
    ameliyattarihi date NOT NULL,
    ameliyatsaati time without time zone,
    CONSTRAINT ameliyat_pkey PRIMARY KEY (ameliyat_id)
);

CREATE TABLE IF NOT EXISTS public.asi
(
    asi_id serial NOT NULL,
    hasta_id integer NOT NULL,
    asituru character varying(50) COLLATE pg_catalog."default" NOT NULL,
    uygulamatarihi date NOT NULL,
    hemsire_id integer,
    CONSTRAINT asi_pkey PRIMARY KEY (asi_id)
);

CREATE TABLE IF NOT EXISTS public.bolum
(
    bolum_id serial NOT NULL,
    bolumadi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    bolumtipi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    bolumsorumlusu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bolum_pkey PRIMARY KEY (bolum_id)
);

CREATE TABLE IF NOT EXISTS public.doktor
(
    doktor_id serial NOT NULL,
    ad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    soyad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    uzmanlik character varying(50) COLLATE pg_catalog."default" NOT NULL,
    bolum_id integer,
    CONSTRAINT doktor_pkey PRIMARY KEY (doktor_id)
);

CREATE TABLE IF NOT EXISTS public.doktorilac
(
    doktorilac_id serial NOT NULL,
    doktor_id integer NOT NULL,
    ilac_id integer NOT NULL,
    CONSTRAINT doktorilac_pkey PRIMARY KEY (doktorilac_id)
);

CREATE TABLE IF NOT EXISTS public.evrak
(
    evrak_id serial NOT NULL,
    hasta_id integer,
    personel_id integer,
    tedavi_id integer,
    evrakturu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    evraktarihi date NOT NULL,
    evrakaciklamasi text COLLATE pg_catalog."default",
    evrakdurumu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT evrak_pkey PRIMARY KEY (evrak_id)
);

CREATE TABLE IF NOT EXISTS public.hasta
(
    hasta_id serial NOT NULL,
    sigorta_id integer,
    ad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    soyad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    uyruk character varying(50) COLLATE pg_catalog."default",
    dogumtarihi date NOT NULL,
    telefon character varying(12) COLLATE pg_catalog."default",
    CONSTRAINT hasta_pkey PRIMARY KEY (hasta_id)
);

CREATE TABLE IF NOT EXISTS public.hastailac
(
    hastailac_id serial NOT NULL,
    hasta_id integer NOT NULL,
    ilac_id integer NOT NULL,
    CONSTRAINT hastailac_pkey PRIMARY KEY (hastailac_id)
);

CREATE TABLE IF NOT EXISTS public.hastalaboratuvar
(
    hastalaboratuvar_id serial NOT NULL,
    hasta_id integer NOT NULL,
    laboratuvar_id integer NOT NULL,
    CONSTRAINT hastalaboratuvar_pkey PRIMARY KEY (hastalaboratuvar_id)
);

CREATE TABLE IF NOT EXISTS public.hastaziyaretci
(
    ziyaretci_id serial NOT NULL,
    hasta_id integer,
    ad character varying(100) COLLATE pg_catalog."default" NOT NULL,
    soyad character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ziyarettarihi date NOT NULL,
    CONSTRAINT hastaziyaretci_pkey PRIMARY KEY (ziyaretci_id)
);

CREATE TABLE IF NOT EXISTS public.hemsire
(
    hemsire_id serial NOT NULL,
    yatanhasta_id integer,
    ad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    soyad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tcno character varying(11) COLLATE pg_catalog."default" NOT NULL,
    telefonno character varying(15) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT hemsire_pkey PRIMARY KEY (hemsire_id),
    CONSTRAINT hemsire_email_key UNIQUE (email),
    CONSTRAINT hemsire_tcno_key UNIQUE (tcno)
);

CREATE TABLE IF NOT EXISTS public.ilac
(
    ilac_id serial NOT NULL,
    doktor_id integer NOT NULL,
    hasta_id integer NOT NULL,
    ilacadi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    doz character varying(50) COLLATE pg_catalog."default",
    ilactipi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ilacfiyat numeric(10, 2),
    uretimtarihi date NOT NULL,
    sonkullanmatarihi date NOT NULL,
    CONSTRAINT ilac_pkey PRIMARY KEY (ilac_id)
);

CREATE TABLE IF NOT EXISTS public.laboratuvar
(
    laboratuvar_id serial NOT NULL,
    laboratuvaradi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    laboratuvartipi character varying(50) COLLATE pg_catalog."default",
    laboratuvartelefon character varying(50) COLLATE pg_catalog."default",
    laboratuvaremail character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT laboratuvar_pkey PRIMARY KEY (laboratuvar_id)
);

CREATE TABLE IF NOT EXISTS public.oda
(
    oda_id serial NOT NULL,
    odanumarasi integer NOT NULL,
    odaturu character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kapasite integer NOT NULL,
    dolu boolean NOT NULL,
    CONSTRAINT oda_pkey PRIMARY KEY (oda_id)
);

CREATE TABLE IF NOT EXISTS public.personel
(
    personel_id serial NOT NULL,
    ad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    soyad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    gorev character varying(50) COLLATE pg_catalog."default" NOT NULL,
    personeltipi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    personelunvan character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefon character varying(50) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT personel_pkey PRIMARY KEY (personel_id),
    CONSTRAINT personel_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.randevu
(
    randevu_id serial NOT NULL,
    hasta_id integer NOT NULL,
    doktor_id integer NOT NULL,
    randevutarihi date NOT NULL,
    randevusaati time without time zone NOT NULL,
    randevudurumu character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT randevu_pkey PRIMARY KEY (randevu_id)
);

CREATE TABLE IF NOT EXISTS public.rapor
(
    rapor_id serial NOT NULL,
    doktor_id integer,
    hasta_id integer,
    raporturu character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tarih date NOT NULL,
    icerik text COLLATE pg_catalog."default",
    CONSTRAINT rapor_pkey PRIMARY KEY (rapor_id)
);

CREATE TABLE IF NOT EXISTS public.sevk
(
    sevk_id serial NOT NULL,
    hasta_id integer NOT NULL,
    doktor_id integer NOT NULL,
    sevkturu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sevknedeni character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sevktarihi date NOT NULL,
    sevksaati time without time zone NOT NULL,
    sevkedilenyer character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sevk_pkey PRIMARY KEY (sevk_id)
);

CREATE TABLE IF NOT EXISTS public.sigorta
(
    sigorta_id serial NOT NULL,
    sigortasirketi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    policenumarasi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sigortaturu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sigortabaslangictarihi date NOT NULL,
    sigortabitistarihi date NOT NULL,
    sigortaucreti numeric(10, 2),
    CONSTRAINT sigorta_pkey PRIMARY KEY (sigorta_id),
    CONSTRAINT sigorta_policenumarasi_key UNIQUE (policenumarasi)
);

CREATE TABLE IF NOT EXISTS public.tahlilvesonuclar
(
    tahlilvesonuclar_id serial NOT NULL,
    hasta_id integer NOT NULL,
    laboratuvar_id integer,
    doktor_id integer NOT NULL,
    tahlilturu character varying(50) COLLATE pg_catalog."default",
    sonuc character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tahlilvesonuclar_pkey PRIMARY KEY (tahlilvesonuclar_id)
);

CREATE TABLE IF NOT EXISTS public.tedavi
(
    tedavi_id serial NOT NULL,
    hasta_id integer,
    doktor_id integer,
    tedavituru character varying(100) COLLATE pg_catalog."default" NOT NULL,
    baslangictarihi date NOT NULL,
    bitistarihi date,
    aciklama text COLLATE pg_catalog."default",
    maliyet numeric(10, 2),
    vezneucret_id integer,
    CONSTRAINT tedavi_pkey PRIMARY KEY (tedavi_id)
);

CREATE TABLE IF NOT EXISTS public.vezneucreti
(
    vezneucreti_id serial NOT NULL,
    hasta_id integer,
    tedavi_id integer,
    ucretturu character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ucrettarihi date NOT NULL,
    ucretmiktari numeric(10, 2),
    odemedurumu character varying(100) COLLATE pg_catalog."default" NOT NULL,
    odemetarihi date,
    CONSTRAINT vezneucreti_pkey PRIMARY KEY (vezneucreti_id)
);

CREATE TABLE IF NOT EXISTS public.yatanhasta
(
    yatanhasta_id serial NOT NULL,
    hasta_id integer,
    oda_id integer,
    yatistarihi date NOT NULL,
    taburcutarihi date,
    CONSTRAINT yatanhasta_pkey PRIMARY KEY (yatanhasta_id)
);

ALTER TABLE IF EXISTS public.ameliyat
    ADD CONSTRAINT "Yapar" FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Yaparr"
    ON public.ameliyat(doktor_id);


ALTER TABLE IF EXISTS public.ameliyat
    ADD CONSTRAINT "Yapilir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ameliyat
    ADD CONSTRAINT "YardimEder" FOREIGN KEY (hemsire_id)
    REFERENCES public.hemsire (hemsire_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_YardimEder"
    ON public.ameliyat(hemsire_id);


ALTER TABLE IF EXISTS public.ameliyat
    ADD CONSTRAINT ameliyat_doktor_id_fkey FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Yaparr"
    ON public.ameliyat(doktor_id);


ALTER TABLE IF EXISTS public.ameliyat
    ADD CONSTRAINT ameliyat_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ameliyat
    ADD CONSTRAINT ameliyat_hemsire_id_fkey FOREIGN KEY (hemsire_id)
    REFERENCES public.hemsire (hemsire_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_YardimEder"
    ON public.ameliyat(hemsire_id);


ALTER TABLE IF EXISTS public.asi
    ADD CONSTRAINT "Yapilir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Yapilir"
    ON public.asi(hasta_id);


ALTER TABLE IF EXISTS public.asi
    ADD CONSTRAINT asi_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Yapilir"
    ON public.asi(hasta_id);


ALTER TABLE IF EXISTS public.asi
    ADD CONSTRAINT asi_hemsire_id_fkey FOREIGN KEY (hemsire_id)
    REFERENCES public.hemsire (hemsire_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.doktor
    ADD CONSTRAINT "Calisir" FOREIGN KEY (bolum_id)
    REFERENCES public.bolum (bolum_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Calisir"
    ON public.doktor(bolum_id);


ALTER TABLE IF EXISTS public.doktor
    ADD CONSTRAINT doktor_bolum_id_fkey FOREIGN KEY (bolum_id)
    REFERENCES public.bolum (bolum_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Calisir"
    ON public.doktor(bolum_id);


ALTER TABLE IF EXISTS public.doktorilac
    ADD CONSTRAINT "IlaciYazilir" FOREIGN KEY (ilac_id)
    REFERENCES public.ilac (ilac_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_IlaciYazilir"
    ON public.doktorilac(ilac_id);


ALTER TABLE IF EXISTS public.doktorilac
    ADD CONSTRAINT "IlaciniYazar" FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_IlaciniYazar"
    ON public.doktorilac(doktor_id);


ALTER TABLE IF EXISTS public.doktorilac
    ADD CONSTRAINT doktorilac_doktor_id_fkey FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_IlaciniYazar"
    ON public.doktorilac(doktor_id);


ALTER TABLE IF EXISTS public.doktorilac
    ADD CONSTRAINT doktorilac_ilac_id_fkey FOREIGN KEY (ilac_id)
    REFERENCES public.ilac (ilac_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_IlaciYazilir"
    ON public.doktorilac(ilac_id);


ALTER TABLE IF EXISTS public.evrak
    ADD CONSTRAINT "Olusturur" FOREIGN KEY (personel_id)
    REFERENCES public.personel (personel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Olusturur"
    ON public.evrak(personel_id);


ALTER TABLE IF EXISTS public.evrak
    ADD CONSTRAINT "Sahiptir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Sahiptir"
    ON public.evrak(hasta_id);


ALTER TABLE IF EXISTS public.evrak
    ADD CONSTRAINT "TedavisineAittir" FOREIGN KEY (tedavi_id)
    REFERENCES public.tedavi (tedavi_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_TedavisineAittir"
    ON public.evrak(tedavi_id);


ALTER TABLE IF EXISTS public.evrak
    ADD CONSTRAINT evrak_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Sahiptir"
    ON public.evrak(hasta_id);


ALTER TABLE IF EXISTS public.evrak
    ADD CONSTRAINT evrak_personel_id_fkey FOREIGN KEY (personel_id)
    REFERENCES public.personel (personel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Olusturur"
    ON public.evrak(personel_id);


ALTER TABLE IF EXISTS public.evrak
    ADD CONSTRAINT evrak_tedavi_id_fkey FOREIGN KEY (tedavi_id)
    REFERENCES public.tedavi (tedavi_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_TedavisineAittir"
    ON public.evrak(tedavi_id);


ALTER TABLE IF EXISTS public.hasta
    ADD CONSTRAINT "Vardir" FOREIGN KEY (sigorta_id)
    REFERENCES public.sigorta (sigorta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Vardir"
    ON public.hasta(sigorta_id);


ALTER TABLE IF EXISTS public.hasta
    ADD CONSTRAINT hasta_sigorta_id_fkey FOREIGN KEY (sigorta_id)
    REFERENCES public.sigorta (sigorta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Vardir"
    ON public.hasta(sigorta_id);


ALTER TABLE IF EXISTS public.hastailac
    ADD CONSTRAINT "IlaciVerilmistir" FOREIGN KEY (ilac_id)
    REFERENCES public.ilac (ilac_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_IlaciVerilmistir"
    ON public.hastailac(ilac_id);


ALTER TABLE IF EXISTS public.hastailac
    ADD CONSTRAINT "IlaciniAlir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_IlaciniAlir"
    ON public.hastailac(hasta_id);


ALTER TABLE IF EXISTS public.hastailac
    ADD CONSTRAINT hastailac_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_IlaciniAlir"
    ON public.hastailac(hasta_id);


ALTER TABLE IF EXISTS public.hastailac
    ADD CONSTRAINT hastailac_ilac_id_fkey FOREIGN KEY (ilac_id)
    REFERENCES public.ilac (ilac_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_IlaciVerilmistir"
    ON public.hastailac(ilac_id);


ALTER TABLE IF EXISTS public.hastalaboratuvar
    ADD CONSTRAINT "KisisininTahliliYapilir" FOREIGN KEY (laboratuvar_id)
    REFERENCES public.laboratuvar (laboratuvar_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_KisisininTahliliYapilir"
    ON public.hastalaboratuvar(laboratuvar_id);


ALTER TABLE IF EXISTS public.hastalaboratuvar
    ADD CONSTRAINT "TahlilYapilir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_S"
    ON public.hastalaboratuvar(hasta_id);


ALTER TABLE IF EXISTS public.hastalaboratuvar
    ADD CONSTRAINT hastalaboratuvar_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_S"
    ON public.hastalaboratuvar(hasta_id);


ALTER TABLE IF EXISTS public.hastalaboratuvar
    ADD CONSTRAINT hastalaboratuvar_laboratuvar_id_fkey FOREIGN KEY (laboratuvar_id)
    REFERENCES public.laboratuvar (laboratuvar_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_KisisininTahliliYapilir"
    ON public.hastalaboratuvar(laboratuvar_id);


ALTER TABLE IF EXISTS public.hastaziyaretci
    ADD CONSTRAINT "RefakatEder" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_RefakatEder"
    ON public.hastaziyaretci(hasta_id);


ALTER TABLE IF EXISTS public.hastaziyaretci
    ADD CONSTRAINT hastaziyaretci_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_RefakatEder"
    ON public.hastaziyaretci(hasta_id);


ALTER TABLE IF EXISTS public.hemsire
    ADD CONSTRAINT "Yapar" FOREIGN KEY (yatanhasta_id)
    REFERENCES public.yatanhasta (yatanhasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Yapar"
    ON public.hemsire(yatanhasta_id);


ALTER TABLE IF EXISTS public.hemsire
    ADD CONSTRAINT hemsire_yatanhasta_id_fkey FOREIGN KEY (yatanhasta_id)
    REFERENCES public.yatanhasta (yatanhasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Yapar"
    ON public.hemsire(yatanhasta_id);


ALTER TABLE IF EXISTS public.ilac
    ADD CONSTRAINT "Kullanir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Kullanir"
    ON public.ilac(hasta_id);


ALTER TABLE IF EXISTS public.ilac
    ADD CONSTRAINT "RecetesiYazar" FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_RecetesiYazar"
    ON public.ilac(doktor_id);


ALTER TABLE IF EXISTS public.ilac
    ADD CONSTRAINT ilac_doktor_id_fkey FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_RecetesiYazar"
    ON public.ilac(doktor_id);


ALTER TABLE IF EXISTS public.ilac
    ADD CONSTRAINT ilac_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Kullanir"
    ON public.ilac(hasta_id);


ALTER TABLE IF EXISTS public.randevu
    ADD CONSTRAINT "Alir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Alir"
    ON public.randevu(hasta_id);


ALTER TABLE IF EXISTS public.randevu
    ADD CONSTRAINT "Bakar" FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Bakar"
    ON public.randevu(doktor_id);


ALTER TABLE IF EXISTS public.randevu
    ADD CONSTRAINT randevu_doktor_id_fkey FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Bakar"
    ON public.randevu(doktor_id);


ALTER TABLE IF EXISTS public.randevu
    ADD CONSTRAINT randevu_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Alir"
    ON public.randevu(hasta_id);


ALTER TABLE IF EXISTS public.rapor
    ADD CONSTRAINT "Hakkindadir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Hak kindadir"
    ON public.rapor(hasta_id);


ALTER TABLE IF EXISTS public.rapor
    ADD CONSTRAINT "Hazirlar" FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Hazirlar"
    ON public.rapor(doktor_id);


ALTER TABLE IF EXISTS public.rapor
    ADD CONSTRAINT rapor_doktor_id_fkey FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Hazirlar"
    ON public.rapor(doktor_id);


ALTER TABLE IF EXISTS public.rapor
    ADD CONSTRAINT rapor_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Hak kindadir"
    ON public.rapor(hasta_id);


ALTER TABLE IF EXISTS public.sevk
    ADD CONSTRAINT "Eder" FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Eder"
    ON public.sevk(doktor_id);


ALTER TABLE IF EXISTS public.sevk
    ADD CONSTRAINT "Edilir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Edilir"
    ON public.sevk(hasta_id);


ALTER TABLE IF EXISTS public.sevk
    ADD CONSTRAINT sevk_doktor_id_fkey FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Eder"
    ON public.sevk(doktor_id);


ALTER TABLE IF EXISTS public.sevk
    ADD CONSTRAINT sevk_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Edilir"
    ON public.sevk(hasta_id);


ALTER TABLE IF EXISTS public.tahlilvesonuclar
    ADD CONSTRAINT "Aittir" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Aittir"
    ON public.tahlilvesonuclar(hasta_id);


ALTER TABLE IF EXISTS public.tahlilvesonuclar
    ADD CONSTRAINT "Ister" FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_İ"
    ON public.tahlilvesonuclar(doktor_id);


ALTER TABLE IF EXISTS public.tahlilvesonuclar
    ADD CONSTRAINT "LaboratuvarindaYapilir" FOREIGN KEY (laboratuvar_id)
    REFERENCES public.laboratuvar (laboratuvar_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_LaboratuvarindaYapilir"
    ON public.tahlilvesonuclar(laboratuvar_id);


ALTER TABLE IF EXISTS public.tahlilvesonuclar
    ADD CONSTRAINT tahlilvesonuclar_doktor_id_fkey FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_İ"
    ON public.tahlilvesonuclar(doktor_id);


ALTER TABLE IF EXISTS public.tahlilvesonuclar
    ADD CONSTRAINT tahlilvesonuclar_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Aittir"
    ON public.tahlilvesonuclar(hasta_id);


ALTER TABLE IF EXISTS public.tahlilvesonuclar
    ADD CONSTRAINT tahlilvesonuclar_laboratuvar_id_fkey FOREIGN KEY (laboratuvar_id)
    REFERENCES public.laboratuvar (laboratuvar_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_LaboratuvarindaYapilir"
    ON public.tahlilvesonuclar(laboratuvar_id);


ALTER TABLE IF EXISTS public.tedavi
    ADD CONSTRAINT "Gorur" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Gorur"
    ON public.tedavi(hasta_id);


ALTER TABLE IF EXISTS public.tedavi
    ADD CONSTRAINT "Uygular" FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Uygular"
    ON public.tedavi(doktor_id);


ALTER TABLE IF EXISTS public.tedavi
    ADD CONSTRAINT tedavi_doktor_id_fkey FOREIGN KEY (doktor_id)
    REFERENCES public.doktor (doktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Uygular"
    ON public.tedavi(doktor_id);


ALTER TABLE IF EXISTS public.tedavi
    ADD CONSTRAINT tedavi_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Gorur"
    ON public.tedavi(hasta_id);


ALTER TABLE IF EXISTS public.tedavi
    ADD CONSTRAINT tedavi_vezneucret_id_fkey FOREIGN KEY (vezneucret_id)
    REFERENCES public.vezneucreti (vezneucreti_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vezneucreti
    ADD CONSTRAINT "Icerir" FOREIGN KEY (tedavi_id)
    REFERENCES public.tedavi (tedavi_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Icerir"
    ON public.vezneucreti(tedavi_id);


ALTER TABLE IF EXISTS public.vezneucreti
    ADD CONSTRAINT "Oder" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Oder"
    ON public.vezneucreti(hasta_id);


ALTER TABLE IF EXISTS public.vezneucreti
    ADD CONSTRAINT vezneucreti_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Oder"
    ON public.vezneucreti(hasta_id);


ALTER TABLE IF EXISTS public.vezneucreti
    ADD CONSTRAINT vezneucreti_tedaviid_fkey FOREIGN KEY (tedavi_id)
    REFERENCES public.tedavi (tedavi_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_Icerir"
    ON public.vezneucreti(tedavi_id);


ALTER TABLE IF EXISTS public.yatanhasta
    ADD CONSTRAINT "HastasiYatar" FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Y"
    ON public.yatanhasta(hasta_id);


ALTER TABLE IF EXISTS public.yatanhasta
    ADD CONSTRAINT "OdasındaYatar" FOREIGN KEY (oda_id)
    REFERENCES public.oda (oda_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_OdasındaYatar"
    ON public.yatanhasta(oda_id);


ALTER TABLE IF EXISTS public.yatanhasta
    ADD CONSTRAINT yatanhasta_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_Y"
    ON public.yatanhasta(hasta_id);


ALTER TABLE IF EXISTS public.yatanhasta
    ADD CONSTRAINT yatanhasta_oda_id_fkey FOREIGN KEY (oda_id)
    REFERENCES public.oda (oda_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "fki_OdasındaYatar"
    ON public.yatanhasta(oda_id);

END;